# Generated by Django 5.1.3 on 2024-12-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='content_type',
            field=models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('video', 'Video')], default='document', max_length=10),
        ),
    ]
