# Generated by Django 5.1.3 on 2024-12-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoAiapp', '0004_alter_post_options_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
